version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestGitDeleteProject
  gitServerName: moaa
  gitUrl: https://github.com/moaaSoftwareAG
  gitUsername: moaaSoftwareAG
  gitBranch: main
services:
- serviceName: project.testgitdelete.integrations:edgeFlow_2
  packages:
  - name: TestGitDeleteProject
    version: "1.0"
- serviceName: project.testgitdelete.integrations:edgeFlow1
  packages:
  - name: TestGitDeleteProject
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.2020
